# Generated by Django 4.1.7 on 2023-04-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mycloud", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="file", name="description",),
    ]
