# Generated by Django 4.1.7 on 2023-04-23 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mycloud", "0003_user_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(name="User_File",),
    ]
