# Generated by Django 4.1.7 on 2023-04-23 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mycloud", "0004_file_users_delete_user_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
