# Generated by Django 4.1.7 on 2023-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycloud", "0006_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
